Repository iterative/gto, pull requests merged in 2022-06, with the labels that each got.

#166 Improve names validation
  gto/config.py
  gto/index.py
  gto/registry.py
  tests/test_config.py
  tests/test_index.py
Labels: breaking-change

#165 Fixing stages lookup
  gto/api.py
  gto/cli.py
  gto/config.py
  gto/registry.py
  gto/utils.py
  tests/test_config.py
Labels: breaking-change

#176 Change 'checkouted' to 'checked out'
  gto/exceptions.py
Labels: bug

#149 Update README.md
  README.md
Labels: documentation
